### ISSUE TITLE
Asynchronous form validation 

### ISSUE THREAD

**Issue by thangngoc89** [Astrocoders/reform#32]
Is there any plan to support async form validation? 
If you can point me to the right direction, I would love to get my hand wet

**Comment by grsabreu** [comment]
Currently the way I'm doing this async validation is using the setError, which sets the global form error in `form.error` in the `onSubmit`

so you can set submitting true, do the validation with the server and then use setError to set `form.error`. It's being enough for me until now.

Something more or less like this
```reason
let onSubmit = (values, ~setError, ~setSubmitting) => {
  Js.Promise.(
    values 
    |> convertToJS
    |> mutate
    |> then_(response => {
        switch(response##error |> Js.Null_undefined.to_opt) {
          | None =>
            setSubmitting(false);
            doSomeOtherThing();
          | Some(error) =>
            setSubmitting(false);
            setError(Some("Something went wrong, try again"))
        }
      })
  )
  |> ignore
}

..in the render
<Form schema onSubmit>
  ...(({ form }) => {
      form.isSubmitting ? <FullLoading /> : {
         <div>
             ...form stuff..

            <FormError error=form.error/> /* form error just handles the option value of error, which is Some(string)*/
         </div>
     }
  })
</Form>
```

Maybe we should include this to the docs in a section "Async Validation with setError"

Do you think your need requires something else?
How would be a nice usage for you?

**Comment by thangngoc89** [comment]
That code looks familiar to me. It's in bs-react-apollo right? 
Anyway, back to the API, I would love be about to do field level validation. Because the current global error API only accepts a string so it's hard to deliver error to each field without some hackings. 

I'm thinkin about extending the schema to support a new type `Async` for example. It would has the API like `Custom` but return a Promise

**Comment by grsabreu** [comment]
we could provide a `CustomAsync(state => Js.Promise.t(option(string)))` validator but idk if that is a good idea because I'm afraid that would lead to a dense code to read. But may be would be ok.
How would be your usage with this per field async validation?
We could also provide another helper to onSubmit, a `setErrorForField(Params.fields, option(string))`, and also change onSubmit to receive a record `{values, setError, setSubmitting, setErrrorForField}` instead of labeled params to avoid unnecessary noise for when you do not need to use all those.
```reason

let onSubmit = ({ setSubmitting, values, setErrorForField }: Form.onSubmitParams) => {
  API.checkEmail(values.email)
 |> then_(isValid => {
  isValid ?
    setSubmitting(false) :
    setErrorForField(`email, Some("This email is already under use"))
 })

 ...etc...
}


<Form
 onSubmit=(onSubmit)
>
```

**Comment by thangngoc89** [comment]
@grsabreu Ah. That's a nice API. My use case is pretty much that. But what about validation info as you type? IMHO, `CustomAsync` is a must.

**Comment by grsabreu** [comment]
got it, I think we can ship this one then!

about the validation as you type, this is the default behavior actually. If we add a CustomAsync we would need to add some kind of throttling I think because to avoid validation in every keystroke.

**Comment by thangngoc89** [comment]
@grsabreu yes. I know it's the default behavior. I just need to be about the do async validation on field level too. Because it's a nice UX feature.

About throttling, it would nice to have it included.

**Comment by grsabreu** [comment]
I think we're going to introduce `setErrorForField` first and then shape better how the AsyncValidation/CustomAsync will be in the code. Because I'm a bit uncertain if this granular async validation per field will enforce good patterns. Maybe having everything to be validate async in `onSubmit` and then set with `setErrorForField` will make the code cleaner, because at least with GraphQL the server errors comes in a single response for the whole call so you would decide in the client for which field that server validation happened.

But I'm open for discussion on this.

How would be your use case for a granular async @thangngoc89 ?

**Comment by thangngoc89** [comment]
@grsabreu This is perfectly fine for me, I'm working on enable that feature for my GraphQL server as well. 

Could you share more about how do you do that with your GraphQL server? We could talk about this on a different platform like reasonml.chat to keep this issue clean

**Comment by grsabreu** [comment]
for sure!
I was thinking in do a demo with my current setup for

**Comment by fakenickels** [comment]
We'll probably use Futures instead of promises here

**Comment by tommmyy** [comment]
I there a progress?

**Comment by fakenickels** [comment]
Probably we'll be back on this as soon as https://github.com/facebook/reason/pull/2487#issuecomment-551219074 lands in master!

**Comment by dan003400** [comment]
Will we have a similar validator like this?

https://github.com/MinimaHQ/re-formality/blob/master/docs/05-AsyncValidation.md

**Comment by dan003400** [comment]
> Probably we'll be back at this as soon as [facebook/reason#2487 (comment)](https://github.com/facebook/reason/pull/2487#issuecomment-551219074) lands in master!

Looks like this has been merged in?
